image: atlassian/default-image:2

pipelines:
  default:
    - step:
        services:
          - docker
        script: 
          - docker login -u $DOCKER_HUB_USER -p $DOCKER_HUB_PASSWORD
          - bash ./build.sh